api_cafeteria_list:
    path: /
    methods: [GET]
    controller: App\Controller\PeopleController::indexAction

api_cafeteria_create:
    path: /
    methods: [POST]
    controller: App\Controller\PeopleController::createAction