general_link_people_to_cafeteria:
    path: /link-people-to-cafeteria
    methods: [GET, POST]
    controller: App\Controller\MainController::linkPeopleToCafeteria

general_link_room_to_coaching:
    path: /link-room-to-coaching
    methods: [GET, POST]
    controller: App\Controller\MainController::linkRoomToCoaching

general_link_people_to_coaching:
    path: /link-people-to-coaching
    methods: [GET, POST]
    controller: App\Controller\MainController::linkPeopleToCoaching

general_find_people:
    path: /find-peoples
    methods: [GET, POST]
    controller: App\Controller\MainController::findPeoples

general_find_room:
    path: /find-rooms
    methods: [GET, POST]
    controller: App\Controller\MainController::findRooms

general_find_cafeteria:
    path: /find-cafeterias
    methods: [GET, POST]
    controller: App\Controller\MainController::findCafeterias
